INSERT INTO users(name, email, password)
  VALUES ('Sandeep', 'sandeepchopra7@gmail.com', 'password'),
  ('Iva Harrison', 'allisonjackson@mail.com', 'password');

INSERT INTO activity(user_id, title, category, duration, completed)
  VALUES (1, 'Shark', 'watch', '120', 0),
  (1, 'Superman', 'watch', '130', 0),
  (1, 'Mcdonalds', 'eat', '30', 0),
  (1, 'Popeyes', 'eat', '30', 1),
  (1, 'Burrate Chicken', 'cook', '100', 0),
  (1, 'Laundry', 'others', '15', 0),
  (1, 'Trim Hedges', 'others', '60', 0),
  (1, 'Superstar', 'watch', '90', 0),
  (1, 'The 3 Brewers', 'eat', '90', 0),
  (1, 'Lasagne', 'cook', '100', 0),
  (1, 'Chicken Fried Rice', 'cook', '45', 0),
  (1, 'Visit Niagara Falls', 'other', '300', 0),
  (1, 'Back-To-School Shopping', 'other', '15', 0),
  (1, 'Harry Potter Marathon', 'watch', '420', 0),
  (1, 'Rick and Morty Marathon', 'watch', '420', 0),
  (1, 'Top Ramen', 'eat', '120', 0),
  (1, 'Panda Express', 'eat', '60', 0),
  (1, 'Visit Auntie May', 'other', '300', 0),
  (1, 'Get Haircut', 'other', '100', 0),
  (1, 'Dye Hair', 'other', '240', 0),
  (1, 'Maccaroni Salad', 'cook', '30', 0),
  (1, 'Beyond Meat Burger', 'cook', '30', 0),
  (1, 'A&W', 'eat', '20', 0),
  (1, 'Go To Library', 'other', '90', 0),
  (1, 'Study Codecademy', 'other', '120', 0),
  (1, 'Get Dog Groomed', 'other', '180', 0),
  (1, 'Read Women Who Run With Wolves', 'other', '20', 0),
  (1, 'Taco Bell', 'eat', '20', 0),
  (1, 'Tacos', 'cook', '45', 0),
  (1, 'Spring Cleaning', 'other', '420', 0),
  (1, 'BBC Oceans', 'watch', '30', 0),
  (1, 'Taquitos', 'watch', '30', 0),
  (1, 'Spicy Noodles', 'cook', '30', 0);
